#!/bin/bash
alias apt-get="sudo apt-get"

# cliqz aliases
alias cliqz-set-aws-env="~/workspace/cliqz/local/bin/setup_cluster_env.sh"
alias cliqz-load-aws-env="source ~/workspace/cliqz/local/bin/load_cluster_env.sh"
alias cliqz-dmz-socks="~/workspace/scripts/cliqz/dmz-ssh"

alias cliqz-check-aws="~/workspace/cliqz/deploy/cluster_tasks.sh check"
alias cliqz-update-depend="~/workspace/cliqz/local/bin/depends.py update"

function cliqz-load-cluster() {
	cliqz-load-aws-env $1
	cliqz-dmz-socks
}

alias cliqz-bim="~/workspace/scripts/screen/bim"
alias cliqz-enzo="~/workspace/scripts/screen/enzo"
alias primary-screen="~/workspace/scripts/screen/x230"
alias ps-ssh="~/workspace/scripts/ssh/ps"

alias pytest="~/workspace/scripts/python/pytest"

function cliqz-test-tmux() {
    ssh -A -t  dmz.fbt.co ssh -t -A $1 'tmux a -t '$2' || /bin/bash'
}

function cliqz-test-ssh() {
    ssh -A -t  dmz.fbt.co ssh -A $1
}

function cliqz-prim-tmux() {
    ssh -A -t  dmz.clyqz.com ssh -t -A $1 'tmux a -t '$2' || /bin/bash'
}

function cliqz-prim-ssh() {
    ssh -A -t  dmz.clyqz.com ssh -A $1
}
