# xrdb -merge ~/.Xresources

## since /etc/X11/xorg.conf.d/01-keyboard-layout.conf
## does not work, we set keyboard layout here
#setxkbmap -layout "us,rs" -option "grp:alt_shift_toggle"
#
## sudo /usr/bin/avfsd -o allow_root -o intr -o sync_read .avfs
#
##while true; do
##  ck-launch-session bash -c "devmon & dwm"
##done
##exec ck-launch-session bash -c "devmon & dwm"
##
#exec dbus-launch --exit-with-session bash -c "udiskie & wmii"
##(sleep 60 && /usr/local/bin/power-off-wlan0)


